### ISSUE TITLE
Cannot load http://localhost:8080 locally

### ISSUE THREAD

**Issue by cvan** [MozVR/HIRO#39]
I start up the local server:

```zsh
% gulp                                                       /opt/HIRO (master)
[18:21:04] Using gulpfile /opt/HIRO/gulpfile.js
[18:21:04] Starting 'express'...
Listening on port 8080
[18:21:04] Finished 'express' after 148 ms
[18:21:04] Starting 'default'...
[18:21:04] Finished 'default' after 3.97 μs
```

Then if I load [http://localhost:8080](http://localhost:8080) in Firefox, I see these errors:

```
GET 
http://localhost:8080/content/sechelt [HTTP/1.1 404 Not Found 0ms]
NS_ERROR_FAILURE:  vrmanager.js:24:0
NS_ERROR_FAILURE:  VRControls.js:37:0
```

![screenshot 2015-03-09 18 23 33](https://cloud.githubusercontent.com/assets/203725/6567704/617e2b96-c689-11e4-87d1-7229a177aa37.png)

**Comment by caseyyee** [comment]
All the content was changed to load locally out of content/ folders for gdc.   Will need to change this back to the public url's where each of the demo's are hosted.

**Comment by caseyyee** [comment]
Resolved as part of https://github.com/MozVR/HIRO/commit/49cdf4c4eb8fb2e3d96bcd051ae7bca45ffc0f00
